required = ["github.com/Unknwon/bra"]

[[constraint]]
  name = "github.com/Jeffail/tunny"
  version = "0.1.1"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-macaron/binding"
  branch = "master"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.3.1"

[[override]]
  name = "github.com/Unknwon/com"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true